name = "NetworkHeaders"
uuid = "b88319e1-9984-40dc-91e8-bdda3b8e5b03"
authors = ["David MacMahon <davidm@astro.berkeley.edu>"]
version = "0.2.1"

[deps]
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[weakdeps]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[extensions]
StructArraysNetworkHeadersExt = "StructArrays"

[compat]
Sockets = "1.11.0"
StructArrays = "0.7.1"
Test = "1.11.0"

[extras]
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StructArrays"]
