module Constants

export IPProtocol, IPPROTO_IP, IPPROTO_ICMP, IPPROTO_IGMP, IPPROTO_IPIP,
    IPPROTO_TCP, IPPROTO_EGP, IPPROTO_PUP, IPPROTO_UDP, IPPROTO_IDP, IPPROTO_TP,
    IPPROTO_DCCP, IPPROTO_IPV6, IPPROTO_RSVP, IPPROTO_GRE, IPPROTO_ESP,
    IPPROTO_AH, IPPROTO_MTP, IPPROTO_BEETPH, IPPROTO_ENCAP, IPPROTO_PIM,
    IPPROTO_COMP, IPPROTO_SCTP, IPPROTO_UDPLITE, IPPROTO_MPLS, IPPROTO_RAW

@enum IPProtocol::UInt8 begin
    IPPROTO_IP = 0
    IPPROTO_ICMP = 1
    IPPROTO_IGMP = 2
    IPPROTO_IPIP = 4
    IPPROTO_TCP = 6
    IPPROTO_EGP = 8
    IPPROTO_PUP = 12
    IPPROTO_UDP = 17
    IPPROTO_IDP = 22
    IPPROTO_TP = 29
    IPPROTO_DCCP = 33
    IPPROTO_IPV6 = 41
    IPPROTO_RSVP = 46
    IPPROTO_GRE = 47
    IPPROTO_ESP = 50
    IPPROTO_AH = 51
    IPPROTO_MTP = 92
    IPPROTO_BEETPH = 94
    IPPROTO_ENCAP = 98
    IPPROTO_PIM = 103
    IPPROTO_COMP = 108
    IPPROTO_SCTP = 132
    IPPROTO_UDPLITE = 136
    IPPROTO_MPLS = 137
    IPPROTO_RAW = 255
end

end # module Constants
